# Generated by Django 3.0.6 on 2020-06-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0003_auto_20200623_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.CharField(choices=[('primary', 'primary'), ('danger', 'danger'), ('secondary', 'secondary')], max_length=15),
        ),
    ]
